### ISSUE TITLE
Purpose of this example

### ISSUE THREAD

**Issue by seongjin-lim** [Lab-CORO/curobo_ros#15]
I tried running rviz.
How do I make the robot move?
In the example written, the robot is not moving.

What happens when you create this trajectory?
ros2 launch curobo_ros gen_traj.launch.py

How do I use the trajectory generated in this command?
ros2 run curobo_ros curobo_gen_traj

Do I need to connect a real camera to the camera?
ros2 launch realsense2_camera rs_launch.py ​​clip_distance:=0.8

I wonder if I need to turn on isaac sim.
Can I run it using curobo python?

**Comment by will-44** [comment]
Hello ! 
This repo is under development, a wiki should come later.
To answer to your questions:
- How do I make the robot move? What happens when you create this trajectory? How do I use the trajectory generated in this command?: You have to launch the launchfile and the node. Then by double click on the arrow in rviz the path should be display. The path is publish on the topic "/trajectory"
- Do I need to connect a real camera to the camera? You can comment this if you don't use cameras
- Can I run it using curobo python? Yes, the purpose of this repo is to remove all dependencies on isaac sim or moveit.

Please feel free to contribute to the project if you wish.
